//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GalleryUploader.ServiceMarunthon {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://marunthon.com/", ConfigurationName="ServiceMarunthon.ApiSoap")]
    public interface ApiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Login(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<int> LoginAsync(string email, string passwordHash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/GetTopEvents", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GalleryUploader.ServiceMarunthon.GetTopEventsResponse GetTopEvents(GalleryUploader.ServiceMarunthon.GetTopEventsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/GetTopEvents", ReplyAction="*")]
        System.Threading.Tasks.Task<GalleryUploader.ServiceMarunthon.GetTopEventsResponse> GetTopEventsAsync(GalleryUploader.ServiceMarunthon.GetTopEventsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/CreateGallery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GalleryUploader.ServiceMarunthon.CreateGalleryResponse CreateGallery(GalleryUploader.ServiceMarunthon.CreateGalleryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/CreateGallery", ReplyAction="*")]
        System.Threading.Tasks.Task<GalleryUploader.ServiceMarunthon.CreateGalleryResponse> CreateGalleryAsync(GalleryUploader.ServiceMarunthon.CreateGalleryRequest request);
        
        // CODEGEN: Parameter 'imageArr' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/SaveImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GalleryUploader.ServiceMarunthon.SaveImageResponse SaveImage(GalleryUploader.ServiceMarunthon.SaveImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://marunthon.com/SaveImage", ReplyAction="*")]
        System.Threading.Tasks.Task<GalleryUploader.ServiceMarunthon.SaveImageResponse> SaveImageAsync(GalleryUploader.ServiceMarunthon.SaveImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopEvents", WrapperNamespace="http://marunthon.com/", IsWrapped=true)]
    public partial class GetTopEventsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=1)]
        public string passwordHash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=2)]
        public string searchFor;
        
        public GetTopEventsRequest() {
        }
        
        public GetTopEventsRequest(string email, string passwordHash, string searchFor) {
            this.email = email;
            this.passwordHash = passwordHash;
            this.searchFor = searchFor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTopEventsResponse", WrapperNamespace="http://marunthon.com/", IsWrapped=true)]
    public partial class GetTopEventsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=0)]
        public System.Data.DataTable GetTopEventsResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=1)]
        public int flag;
        
        public GetTopEventsResponse() {
        }
        
        public GetTopEventsResponse(System.Data.DataTable GetTopEventsResult, int flag) {
            this.GetTopEventsResult = GetTopEventsResult;
            this.flag = flag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateGallery", WrapperNamespace="http://marunthon.com/", IsWrapped=true)]
    public partial class CreateGalleryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=1)]
        public string passwordHash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=2)]
        public int eventId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=3)]
        public string galleryName;
        
        public CreateGalleryRequest() {
        }
        
        public CreateGalleryRequest(string email, string passwordHash, int eventId, string galleryName) {
            this.email = email;
            this.passwordHash = passwordHash;
            this.eventId = eventId;
            this.galleryName = galleryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateGalleryResponse", WrapperNamespace="http://marunthon.com/", IsWrapped=true)]
    public partial class CreateGalleryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=0)]
        public int CreateGalleryResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=1)]
        public int flag;
        
        public CreateGalleryResponse() {
        }
        
        public CreateGalleryResponse(int CreateGalleryResult, int flag) {
            this.CreateGalleryResult = CreateGalleryResult;
            this.flag = flag;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveImage", WrapperNamespace="http://marunthon.com/", IsWrapped=true)]
    public partial class SaveImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=1)]
        public string passwordHash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=2)]
        public int galleryId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] imageArr;
        
        public SaveImageRequest() {
        }
        
        public SaveImageRequest(string email, string passwordHash, int galleryId, byte[] imageArr) {
            this.email = email;
            this.passwordHash = passwordHash;
            this.galleryId = galleryId;
            this.imageArr = imageArr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveImageResponse", WrapperNamespace="http://marunthon.com/", IsWrapped=true)]
    public partial class SaveImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://marunthon.com/", Order=0)]
        public int SaveImageResult;
        
        public SaveImageResponse() {
        }
        
        public SaveImageResponse(int SaveImageResult) {
            this.SaveImageResult = SaveImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiSoapChannel : GalleryUploader.ServiceMarunthon.ApiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiSoapClient : System.ServiceModel.ClientBase<GalleryUploader.ServiceMarunthon.ApiSoap>, GalleryUploader.ServiceMarunthon.ApiSoap {
        
        public ApiSoapClient() {
        }
        
        public ApiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int Login(string email, string passwordHash) {
            return base.Channel.Login(email, passwordHash);
        }
        
        public System.Threading.Tasks.Task<int> LoginAsync(string email, string passwordHash) {
            return base.Channel.LoginAsync(email, passwordHash);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GalleryUploader.ServiceMarunthon.GetTopEventsResponse GalleryUploader.ServiceMarunthon.ApiSoap.GetTopEvents(GalleryUploader.ServiceMarunthon.GetTopEventsRequest request) {
            return base.Channel.GetTopEvents(request);
        }
        
        public System.Data.DataTable GetTopEvents(string email, string passwordHash, string searchFor, out int flag) {
            GalleryUploader.ServiceMarunthon.GetTopEventsRequest inValue = new GalleryUploader.ServiceMarunthon.GetTopEventsRequest();
            inValue.email = email;
            inValue.passwordHash = passwordHash;
            inValue.searchFor = searchFor;
            GalleryUploader.ServiceMarunthon.GetTopEventsResponse retVal = ((GalleryUploader.ServiceMarunthon.ApiSoap)(this)).GetTopEvents(inValue);
            flag = retVal.flag;
            return retVal.GetTopEventsResult;
        }
        
        public System.Threading.Tasks.Task<GalleryUploader.ServiceMarunthon.GetTopEventsResponse> GetTopEventsAsync(GalleryUploader.ServiceMarunthon.GetTopEventsRequest request) {
            return base.Channel.GetTopEventsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GalleryUploader.ServiceMarunthon.CreateGalleryResponse GalleryUploader.ServiceMarunthon.ApiSoap.CreateGallery(GalleryUploader.ServiceMarunthon.CreateGalleryRequest request) {
            return base.Channel.CreateGallery(request);
        }
        
        public int CreateGallery(string email, string passwordHash, int eventId, string galleryName, out int flag) {
            GalleryUploader.ServiceMarunthon.CreateGalleryRequest inValue = new GalleryUploader.ServiceMarunthon.CreateGalleryRequest();
            inValue.email = email;
            inValue.passwordHash = passwordHash;
            inValue.eventId = eventId;
            inValue.galleryName = galleryName;
            GalleryUploader.ServiceMarunthon.CreateGalleryResponse retVal = ((GalleryUploader.ServiceMarunthon.ApiSoap)(this)).CreateGallery(inValue);
            flag = retVal.flag;
            return retVal.CreateGalleryResult;
        }
        
        public System.Threading.Tasks.Task<GalleryUploader.ServiceMarunthon.CreateGalleryResponse> CreateGalleryAsync(GalleryUploader.ServiceMarunthon.CreateGalleryRequest request) {
            return base.Channel.CreateGalleryAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GalleryUploader.ServiceMarunthon.SaveImageResponse GalleryUploader.ServiceMarunthon.ApiSoap.SaveImage(GalleryUploader.ServiceMarunthon.SaveImageRequest request) {
            return base.Channel.SaveImage(request);
        }
        
        public int SaveImage(string email, string passwordHash, int galleryId, byte[] imageArr) {
            GalleryUploader.ServiceMarunthon.SaveImageRequest inValue = new GalleryUploader.ServiceMarunthon.SaveImageRequest();
            inValue.email = email;
            inValue.passwordHash = passwordHash;
            inValue.galleryId = galleryId;
            inValue.imageArr = imageArr;
            GalleryUploader.ServiceMarunthon.SaveImageResponse retVal = ((GalleryUploader.ServiceMarunthon.ApiSoap)(this)).SaveImage(inValue);
            return retVal.SaveImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GalleryUploader.ServiceMarunthon.SaveImageResponse> GalleryUploader.ServiceMarunthon.ApiSoap.SaveImageAsync(GalleryUploader.ServiceMarunthon.SaveImageRequest request) {
            return base.Channel.SaveImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<GalleryUploader.ServiceMarunthon.SaveImageResponse> SaveImageAsync(string email, string passwordHash, int galleryId, byte[] imageArr) {
            GalleryUploader.ServiceMarunthon.SaveImageRequest inValue = new GalleryUploader.ServiceMarunthon.SaveImageRequest();
            inValue.email = email;
            inValue.passwordHash = passwordHash;
            inValue.galleryId = galleryId;
            inValue.imageArr = imageArr;
            return ((GalleryUploader.ServiceMarunthon.ApiSoap)(this)).SaveImageAsync(inValue);
        }
    }
}
